### ISSUE TITLE
Typo in the example

### ISSUE THREAD

**Issue by Miguel-M-O** [abardet/methylasso#1]
Hi!, 

I tested the code in my computer with the example files and there is a typo that gives back an error.  The separation between the replicates in each condition should be without spaces after the comma. 

Rscript MethyLasso.R --n1 normal --c1 WGBS_normal_1_chr1_meth.bed.gz,WGBS_normal_2_chr1_meth.bed.gz,WGBS_normal_3_chr1_meth.bed.gz --n2 cancer --c2 WGBS_cancer_1_chr1_meth.bed.gz,WGBS_cancer_2_chr1_meth.bed.gz,WGBS_cancer_3_chr1_meth.bed.gz --cov 4 --meth 5 -q 0.05

**Comment by delbala** [comment]
Hi, 

Thank you for pointing out the typo!

Delphine

**Comment by abardet** [comment]
Dear Miguel-M-O,
For your information, if you were using bismark output files as input to MethyLasso, we just fixed an issue in MethyLasso.R to take the correct columns as input so this file should be replaced or options "--mC 5 --uC 6" specified.
I'm very sorry for that.
Best,
Anaïs
