### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by secabhk001** [abardet/methylasso#2]
As per the README file, we need to have the "MethyLasso.tar.gz" &  "conda_env.yml" files , but I couldn't find the files in the github repository. 
$ ls
DESCRIPTION  input  LICENSE  man  MethyLasso.R  NAMESPACE  R  README.md  src
$ R CMD INSTALL --preclean MethyLasso
Warning: invalid package ‘MethyLasso’
Error: ERROR: no packages specified

Environment Details: 
R version : 4.3.0 (2023-04-21)
OS : RHEL7.9
Python : 3.10.10

Kindly suggest the way to install MethyLasso. 
Thanks.

**Comment by delbala** [comment]
Hello ,

Thank you for bringing this to my attention. I apologize for any inconvenience you've experienced regarding the missing file. I have taken the necessary steps to resolve this issue.
I have now added the "conda_env.yml" file to the GitHub repository. You should be able to use it to create the Conda environment required for MethyLasso. 

Delphine

**Comment by abardet** [comment]
Dear secabhk001,
For your information, if you were using bismark output files as input to MethyLasso, we just fixed an issue in MethyLasso.R to take the correct columns as input so this file should be replaced or options "--mC 5 --uC 6" specified.
I'm very sorry for that.
Best,
Anaïs
