### ISSUE TITLE
Can't find methylasso-main.zip 

### ISSUE THREAD

**Issue by desmodus1984** [abardet/methylasso#3]
Hi,
I work with bumblebee methylation and I am interested in testing your software with my samples to see what pattern/results I get.

I was going to install it but I can't find the file: methylasso-main.zip.
Is it in github yet?

**Comment by delbala** [comment]
Hi, 

MethyLasso package is available on github by clicking on the green “Code” thumbnail then "download ZIP".
You can also download it by clicking on this link:
https://github.com/abardet/methylasso/archive/refs/heads/main.zip

Delphine

**Comment by abardet** [comment]
Dear desmodus1984,
For your information, if you were using bismark output files as input to MethyLasso, we just fixed an issue in MethyLasso.R to take the correct columns as input so this file should be replaced or options "--mC 5 --uC 6" specified.
I'm very sorry for that.
Best,
Anaïs
